# Generated by Django 3.1.6 on 2021-05-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_item_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placed_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer3', to='eshop.customer')),
                ('items', models.ManyToManyField(to='eshop.Item')),
            ],
        ),
    ]
