# Generated by Django 3.1.6 on 2021-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_placed_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_order',
            name='items',
        ),
        migrations.AddField(
            model_name='placed_order',
            name='items',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
