# Generated by Django 3.1.6 on 2021-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20210503_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_order',
            name='i',
            field=models.IntegerField(default=0),
        ),
    ]
